### ISSUE TITLE
couverture par les programme de test a 100%

### ISSUE THREAD

**Issue by alanjaouen** [alanJaouen/miniprojet#2]
couverture par les programme de test a 100%

**Comment by Zanorin** [comment]
wattafock


________________________________

**Comment by alanjaouen** [comment]
casse les couilles d'avoir des issues pas fermées sur mon github x)

**Comment by Zanorin** [comment]
pourquoi je suis inscrite a ca? XD


________________________________

**Comment by alanjaouen** [comment]
On s'en est servi en gestion de projet / gradle
